### ISSUE TITLE
PubSub - Insufficient In-Depth Technical Documentation on the Acknowledgment Process during Message Processing

### ISSUE THREAD

**Issue by Vity01** [googleapis/java-pubsub#1690]
I need to address a situation where the message processing usually exceeds the maximum ACK deadline of 600 seconds. To manage ACK timeout periods effectively, I can utilize three properties in the spring.cloud.gcp.pubsub.subscriber configuration:
```
spring:
  cloud:
    gcp:
      pubsub:
        subscriber:
          max-ack-extension-period: xx
          min-duration-per-ack-extension: xx
          max-duration-per-ack-extension: xx
```
However, the current description of these properties, as provided in the documentation (https://cloud.google.com/pubsub/docs/lease-management#lease_management_configuration), is quite cryptic. These values play a crucial role in the `com.google.cloud.pubsub.v1.MessageDispatcher`, but the code implementation is not easy to comprehend. Additionally, it is not evident whether the extension period mechanism should be invoked manually or what the default behavior is. I did not find any description.

To provide clearer understanding and assistance, it would be beneficial to include the following:
-    An illustrative image, possibly in the form of a UML sequence diagram, to demonstrate how the ACK and extension period work and how these values are utilized.
-  Real-world examples showcasing recommended settings and values for various scenarios, particularly when the processing of a single message takes anywhere between 5 to 30 minutes.
